services:
  next:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: webask_app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
    depends_on:
      - db
    networks:
      - webask_network

  db:
    image: mysql:8.0
    container_name: webask_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: webask_db
      MYSQL_USER: webask_user
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - webask_network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: webask_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8082:80"
    depends_on:
      - db
    networks:
      - webask_network

volumes:
  db_data:

networks:
  webask_network:
    driver: bridge